### ISSUE TITLE
import error: pkg_resources

### ISSUE THREAD

**Issue by rbubley** [gae-init/gae-init-debug#4]
Using a fresh gae-init-debug, (pulling in latest changes from gae-init), I get the following error:

```
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.80:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.80:3001
 -------------------------------------
INFO     2018-02-22 20:12:24,765 devappserver2.py:105] Skipping SDK update check.
INFO     2018-02-22 20:12:25,038 api_server.py:265] Starting API server at: http://localhost:61897
INFO     2018-02-22 20:12:25,140 dispatcher.py:255] Starting module "default" running at: http://127.0.0.1:8080
INFO     2018-02-22 20:12:25,149 admin_server.py:152] Starting admin server at: http://localhost:8081
ERROR    2018-02-22 20:12:29,552 wsgi.py:263] 
Traceback (most recent call last):
  File "/Users/russ/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/russ/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/russ/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/russ/gae-init-debug/main/main.py", line 28, in <module>
    toolbar = flask_debugtoolbar.DebugToolbarExtension(app)
  File "lib/flask_debugtoolbar/__init__.py", line 53, in __init__
    loader=PackageLoader(__name__, 'templates'))
  File "/Users/russ/google-cloud-sdk/platform/google_appengine/lib/jinja2-2.6/jinja2/loaders.py", line 214, in __init__
    from pkg_resources import DefaultProvider, ResourceManager, \
ImportError: No module named pkg_resources
INFO     2018-02-22 20:12:29,583 module.py:835] default: "GET /_ah/warmup HTTP/1.1" 500 749
```

**Comment by lipis** [comment]
Haven't tested in a while.. :) Let me see..

**Comment by lipis** [comment]
#5 with a quick look not sure why?

**Comment by rbubley** [comment]
I couldn’t immediately see if it was one of these changes or if it is some sort of environment change with the Google SDK.

**Comment by rbubley** [comment]
Without figuring out *why* we are getting the error, I found that the error goes away if we copy `pkg_resources.py` into either `main` or `main/lib`.  Any views on how/where you would like the file @lipis ?
